### ISSUE TITLE
Add the component to HACS

### ISSUE THREAD

**Issue by maicol07** [ollo69/ha_asuswrt_custom#3]
Hi,
can you add the component to HACS?
https://hacs.xyz/docs/publish/start
Thanks

**Comment by ollo69** [comment]
Because the goal of this custom integration is to test this implementation waiting for same code in [PR #71899](https://github.com/home-assistant/core/pull/71899) being review and eventually merged in native integration, I prefer to not add this to HACS default. You can anyway add it to your HACS custom repository to use HACS to manage installation and upgrade

**Comment by maicol07** [comment]
Thank you. For reference here's the docs page about it: https://hacs.xyz/docs/faq/custom_repositories
